package email_client;

import email_client.global.GithubProfile;
import email_client.global.IconImageUtilities;
import email_client.global.LookandFeel;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

public class anotherAboutTeam extends javax.swing.JFrame {
    
    GithubProfile profileLink = new GithubProfile();
    
    /**
     * Creates new form anotherAboutTeam
     */
    public anotherAboutTeam() {
        initComponents();
        IconImageUtilities.setIconImage(this);
        firstGithub.setText("<html> <a href=\"\">"+ profileLink.getTwodgirlsismywaifu() +"</a></html>");
        secondGithub.setText("<html> <a href=\"\">"+ profileLink.getPhoebeHa0320() +"</a></html>");
        thirdGithub.setText("<html> <a href=\"\">"+ profileLink.getNgohien0810() +"</a></html>");
        fourthGithub.setText("<html> <a href=\"\">"+ profileLink.getLedat220497() +"</a></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new email_client.global.ImageAvatar();
        imageAvatar2 = new email_client.global.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstGithub = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secondGithub = new javax.swing.JLabel();
        imageAvatar3 = new email_client.global.ImageAvatar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        thirdGithub = new javax.swing.JLabel();
        imageAvatar4 = new email_client.global.ImageAvatar();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fourthGithub = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin nhóm");
        setResizable(false);

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/90584137.jpg"))); // NOI18N

        imageAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/59259855.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Ngô Thành Long");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Email: ngothanhlong19943@gmail.com");

        firstGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstGithub.setText("github");
        firstGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstGithubMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nguyễn Ngọc Hoàng Hà");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Email: hoangha2000@gmail.com");

        secondGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        secondGithub.setText("github");
        secondGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondGithubMouseClicked(evt);
            }
        });

        imageAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/47359493.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Ngô Thị Hiền");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Email: ngohien0810@gmail.com");

        thirdGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        thirdGithub.setText("github");
        thirdGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thirdGithubMouseClicked(evt);
            }
        });

        imageAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/picture_profile/70122193.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Lê Tiến Đạtl");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Email: ledat199x97@gmail.com");

        fourthGithub.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fourthGithub.setText("github");
        fourthGithub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourthGithubMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nhóm 7: Email Client Manager - Quản lý Email người dùng");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("@2dgirlismywaifu");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("@PhoebeHa0320");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("@ngohien0810");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("@ledat220497");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstGithub)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secondGithub)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thirdGithub)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fourthGithub)))
                                    .addComponent(jLabel13)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel12)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel12)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6)
                                .addGap(15, 15, 15)
                                .addComponent(thirdGithub))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel10)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addGap(15, 15, 15)
                                .addComponent(firstGithub))
                            .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)
                        .addComponent(secondGithub))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel13)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)
                        .addGap(15, 15, 15)
                        .addComponent(fourthGithub))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(imageAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstGithubMouseClicked
        // TODO add your handling code here:
        firstGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getTwodgirlsismywaifu());
    }//GEN-LAST:event_firstGithubMouseClicked

    private void secondGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondGithubMouseClicked
        // TODO add your handling code here:
        secondGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getPhoebeHa0320());
    }//GEN-LAST:event_secondGithubMouseClicked

    private void thirdGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdGithubMouseClicked
        // TODO add your handling code here:
        thirdGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getNgohien0810());
    }//GEN-LAST:event_thirdGithubMouseClicked

    private void fourthGithubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourthGithubMouseClicked
        // TODO add your handling code here:
        fourthGithub.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goToProfile(profileLink.getLedat220497());
    }//GEN-LAST:event_fourthGithubMouseClicked
    
    private void goToProfile(String url) {
        try {
            Desktop.getDesktop().browse(new URI(url));
        } catch (URISyntaxException | IOException ex) {
                ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        LookandFeel.setTheme();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new anotherAboutTeam().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstGithub;
    private javax.swing.JLabel fourthGithub;
    private email_client.global.ImageAvatar imageAvatar1;
    private email_client.global.ImageAvatar imageAvatar2;
    private email_client.global.ImageAvatar imageAvatar3;
    private email_client.global.ImageAvatar imageAvatar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel secondGithub;
    private javax.swing.JLabel thirdGithub;
    // End of variables declaration//GEN-END:variables
}
